use_frameworks!

target 'SwiftData' do
    pod 'Moya/RxSwift'
    pod 'RxRealm'
    pod 'RxCocoa'
    pod 'GDataXML-HTML', '~> 1.4.1'
    pod 'SwiftyJSON'
    pod 'MJExtension'
    pod 'CocoaAsyncSocket' 
end
