source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
pod 'CocoaLumberjack', '3.4.1'
pod 'AFNetworking', '3.2.0'
pod 'WCDB','1.0.6'
pod 'MJExtension', '3.0.13'
pod 'ReactiveObjC', '3.1.0'
pod 'MBProgressHUD', '0.9.2'
pod 'CocoaAsyncSocket', '7.6.3'
pod 'Masonry', '1.1.0'
pod 'GDataXML-HTML', '1.4.1'
pod 'RxSwift',    '~> 4.0'
pod 'RxCocoa',    '~> 4.0'
pod 'RxGesture',    '~> 1.2.1'
pod 'SDWebImage', '~> 4.0'
target ‘Project’ do
end
