//
//  TCLConfigModel+WCTTableCoding.h
//  Project
//
//  Created by lingda on 2018/10/18.
//  Copyright © 2018年 令达. All rights reserved.
//

#import "ConfigModel.h"
#import <WCDB/WCDB.h>

@interface ConfigModel (WCTTableCoding) <WCTTableCoding>
WCDB_PROPERTY(newhelpandroid)
WCDB_PROPERTY(newhelpios)
WCDB_PROPERTY(clkdev)
WCDB_PROPERTY(cateoptinfosversion)
WCDB_PROPERTY(companyname)
WCDB_PROPERTY(serviceagreement)
WCDB_PROPERTY(tvbindphoneurl)
WCDB_PROPERTY(scenedevicon)
WCDB_PROPERTY(reconcnt)
WCDB_PROPERTY(scanuseridurl)
WCDB_PROPERTY(reqsharedevurl)
WCDB_PROPERTY(helpandroid)
WCDB_PROPERTY(sharecbctime)
WCDB_PROPERTY(logontimeoutlen)
WCDB_PROPERTY(banner)
WCDB_PROPERTY(iOSConfigConsistant)
WCDB_PROPERTY(ad)
WCDB_PROPERTY(brandname)
WCDB_PROPERTY(configConsistant)
WCDB_PROPERTY(invitecontent)
WCDB_PROPERTY(helpios)
WCDB_PROPERTY(acdirections)
WCDB_PROPERTY(backreconinterval)
WCDB_PROPERTY(configversion)
WCDB_PROPERTY(wifiexchangelimit)
WCDB_PROPERTY(sceneversion)
WCDB_PROPERTY(uploadsizelimit)
WCDB_PROPERTY(bannerpic)
WCDB_PROPERTY(reconinterval)
WCDB_PROPERTY(heartbeattime)
WCDB_PROPERTY(privacypolicy)
WCDB_PROPERTY(reportvideotime)
WCDB_PROPERTY(sharedevurl)
WCDB_PROPERTY(iOSWifiPrivateAPI)
WCDB_PROPERTY(clkdevs)
WCDB_PROPERTY(apconfig)
WCDB_PROPERTY(logontimeoutcnt)
WCDB_PROPERTY(flatlocationversion)
WCDB_PROPERTY(categoryname)

WCDB_PROPERTY(randCode)
WCDB_PROPERTY(currentUserID)

@end





@interface SceneDevIconModel(WCTTableCoding) <WCTTableCoding>
WCDB_PROPERTY(annica)
WCDB_PROPERTY(AB)
WCDB_PROPERTY(MM)
WCDB_PROPERTY(bql)
WCDB_PROPERTY(DSeries)
WCDB_PROPERTY(GD)
WCDB_PROPERTY(ZJRQR)
WCDB_PROPERTY(ZJRQR2P)
WCDB_PROPERTY(SPFWASUB)
WCDB_PROPERTY(SP)
WCDB_PROPERTY(SW)
WCDB_PROPERTY(SW1)
WCDB_PROPERTY(SW2)
WCDB_PROPERTY(SW3)
WCDB_PROPERTY(SW4)
WCDB_PROPERTY(DS)
WCDB_PROPERTY(xhyds)
WCDB_PROPERTY(ECT)
WCDB_PROPERTY(ECT_100)
WCDB_PROPERTY(VM)
WCDB_PROPERTY(hmvm)
WCDB_PROPERTY(EF)
WCDB_PROPERTY(BS)
WCDB_PROPERTY(SOS)
WCDB_PROPERTY(hmsos)
WCDB_PROPERTY(hmbs)
WCDB_PROPERTY(LioneerSWO)
WCDB_PROPERTY(SWO)
WCDB_PROPERTY(ZHSWO)
WCDB_PROPERTY(CLKSN95Y)
WCDB_PROPERTY(CLF6NK4U)
WCDB_PROPERTY(CL)
WCDB_PROPERTY(AC)
WCDB_PROPERTY(LY)
WCDB_PROPERTY(BCD_216)
WCDB_PROPERTY(GS)
WCDB_PROPERTY(hmgs)
WCDB_PROPERTY(GL)
WCDB_PROPERTY(tsgl)
WCDB_PROPERTY(SLK)
WCDB_PROPERTY(WDR_200)
WCDB_PROPERTY(PDB)
WCDB_PROPERTY(ToseePDB)
WCDB_PROPERTY(ZSC)
WCDB_PROPERTY(ZSC4)
WCDB_PROPERTY(RT)
WCDB_PROPERTY(RT249B01)
WCDB_PROPERTY(CA)
WCDB_PROPERTY(ID)
WCDB_PROPERTY(hmid)
WCDB_PROPERTY(EFRBPKS5)
WCDB_PROPERTY(zmwl)
WCDB_PROPERTY(PW)
WCDB_PROPERTY(DW)
WCDB_PROPERTY(SD)
WCDB_PROPERTY(hmsd)
WCDB_PROPERTY(JSSeries)
WCDB_PROPERTY(SC)
WCDB_PROPERTY(htgw)
WCDB_PROPERTY(GW)
WCDB_PROPERTY(WH)
WCDB_PROPERTY(EWH)
WCDB_PROPERTY(Z2)
WCDB_PROPERTY(WRS)
WCDB_PROPERTY(LioneerWRS)
WCDB_PROPERTY(RF)
WCDB_PROPERTY(ISeries)
WCDB_PROPERTY(TRO)
WCDB_PROPERTY(enecai)
WCDB_PROPERTY(WL)
WCDB_PROPERTY(zmlb)
WCDB_PROPERTY(TV)
WCDB_PROPERTY(GowildRT)
WCDB_PROPERTY(RaysgemMM)
WCDB_PROPERTY(SS)
WCDB_PROPERTY(zytdsp_chn)
@end

@interface SceneVersionModel(WCTTableCoding) <WCTTableCoding>

WCDB_PROPERTY(cstconditionver)
WCDB_PROPERTY(cstactionver)
WCDB_PROPERTY(devconditionver)
WCDB_PROPERTY(devactionver)

@end

@interface NameModel(WCTTableCoding) <WCTTableCoding>

WCDB_PROPERTY(enname)
WCDB_PROPERTY(znname)
@end

@interface ADModel(WCTTableCoding) <WCTTableCoding>

WCDB_PROPERTY(pic)
WCDB_PROPERTY(link)
@end

@interface CLKDevsModel(WCTTableCoding) <WCTTableCoding>

WCDB_PROPERTY(ctgr)
WCDB_PROPERTY(page)
@end

@interface APConfigModel(WCTTableCoding) <WCTTableCoding>

WCDB_PROPERTY(company)
WCDB_PROPERTY(category)
WCDB_PROPERTY(ip)
WCDB_PROPERTY(port)
WCDB_PROPERTY(pwd)
@end

@interface CategorynameModel(WCTTableCoding) <WCTTableCoding>

WCDB_PROPERTY(company)
WCDB_PROPERTY(brand)
WCDB_PROPERTY(enname)
WCDB_PROPERTY(znname)
WCDB_PROPERTY(bgtitle)
WCDB_PROPERTY(level)
WCDB_PROPERTY(head)
@end
